apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app-of-apps-visualizer.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: app-of-app-visualizer
    app.kubernetes.io/part-of: app-of-app-visualizer
  {{- include "app-of-apps-visualizer.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}