# permissions for end users to view appversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: appversion-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: app-of-app-visualizer
    app.kubernetes.io/part-of: app-of-app-visualizer
    app.kubernetes.io/managed-by: kustomize
  name: appversion-viewer-role
rules:
- apiGroups:
  - visualization.magiccicd
  resources:
  - appversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - visualization.magiccicd
  resources:
  - appversions/status
  verbs:
  - get
