---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - visualization.magiccicd
  resources:
  - appofapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - visualization.magiccicd
  resources:
  - appofapps/finalizers
  verbs:
  - update
- apiGroups:
  - visualization.magiccicd
  resources:
  - appofapps/status
  verbs:
  - get
  - patch
  - update
